How to install Prometheus on CentOS 8
hetzneronline/community-content pull request #252
Opened 2020-08-06 20:26 UTC by outdat3dkernel

2020-08-12 06:41 UTC, BackInBash commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +---
You should remove the empty lines.

2020-08-13 12:14 UTC, outdat3dkernel commented
Should be OK now..

2020-08-20 10:53 UTC, n-se requested changes
Thank you for your tutorial. I have added some notes.

Please remove all the surplus newlines in your tutorial.
This tutorial should also work on any other Linux system like Debian / Ubuntu / etc.
Please also add a notice about newer versions every time you download from a github release in your tutorial.

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +author_img: "https://avatars0.githubusercontent.com/u/47123910?s=460&u=60ae9274465379d8402403cd49f9a0384c82d8a9&v=4"
```suggestion
author_img: "https://avatars0.githubusercontent.com/u/47123910"
```

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +## What is Prometheus?
That can be part of your actual Introduction, no need for a second Introduction

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +touch /etc/systemd/system/prometheus.service
No need to touch the file manually, you can just create it with nano below

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +touch /etc/systemd/system/node_exporter.service
Please replace touch with nano as you did above

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> +![Prometheus node_exporter](https://i.imgur.com/SRNNGX3.png)
Please upload this image to your tutorial folder instead of using imgur

2020-08-20 10:53 UTC, n-se commented on tutorials/howto-install-prometheus-on-centos8/01.en.md
> ++ Ports `9090` and `9100` allowed in the firewall (if any configured)
9090 -  ok maybe if you want to scrape prometheus from an external system
9100 - not really because you scrape the node exporter from localhost

2020-10-05 06:01 UTC, rook59 commented
@outdat3dkernel maybe you missed my other comments since you only committed one change? :)

2020-11-25 11:38 UTC, rook59 commented
Do you still plan to work on this tutorial?

2021-02-08 08:13 UTC, rook59 commented
@outdat3dkernel do you still plan to work on this tutorial?

2021-02-22 12:27 UTC, rook59 commented
If you want to finish this tutorial please let us know and we can reopen your PR. :)

2021-02-22 12:27 UTC, closed without merging