tutorial for Nextcloud
hetzneronline/community-content pull request #273
Opened 2020-10-26 17:30 UTC by rericsson

Hi, 

I've created a new tutorial for installing and configuring Nextcloud on Hetzner. 

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Rob Ericsson rob@l10systems.com

2020-11-19 11:20 UTC, rook59 requested changes
Thank you for your submission.

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +* A local [hcloud](https://github.com/hetznercloud/cli) CLI install
You could link to https://community.hetzner.com/tutorials/howto-hcloud-cli here

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +The tutorial uses the following conventions to represent variables used in the code below:
Actually we pre-defined the terminology of those in the template https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md#introduction

Though I think we can keep it that way too. @leojakeson what do you think?

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +sudo snap install nextcloud
The `$` is missing here

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +sudo nextcloud.manual-install <your_user_name> <your_password>
The `$` is missing here

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +To keep this simple, we will use a self-signed certificate to enable encryption on our server. This type of certificate will show warnings in our browser when we access our Nextcloud site but that is
Can you please explain or at least reference something were I can find more information about how to configure my own domain and a valid SSL certificate? I don't think anyone really wants to remember an IP address even for private use.
Maybe you can use something like the Nginx with LE on Debian 10 tutorial here? https://community.hetzner.com/tutorials/install-and-secure-nginx-lets-encrypt-debian-10

There is also `nextcloud.enable-https lets-encrypt`

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +title: "Install and Configure Nextcloud"
```suggestion
title: "Install and Configure Nextcloud using Snap"
```

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +short_description: "This tutorial has step-by-step instructions to install and configure Nextcloud in the Hetzner Cloud for filesharing and groupware"
```suggestion
short_description: "This tutorial has step-by-step instructions to install and configure Nextcloud using Snap in the Hetzner Cloud for filesharing and groupware"
```

2020-11-19 11:20 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +tags: ["Nextcloud", "Ubuntu"]
```suggestion
tags: ["Nextcloud", "Ubuntu", "Snap"]
```

2020-11-19 11:21 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +* <network_id> is the name of the network used for the cluster. e.g. network-1
No network required here

2020-12-06 16:28 UTC, rericsson commented
Made some fixes to address the feedback.

2020-12-09 14:10 UTC, rook59 commented on tutorials/install-and-configure-nextcloud/01.en.md
> +To create a self-signed certificate, run:
Self signed is better but still not that nice. Can you please explain `nextcloud.enable-https lets-encrypt`? It looks quite simple to me to get a valid SSL certificate through this snap command so worth explaining.

2020-12-16 18:50 UTC, rericsson commented on tutorials/install-and-configure-nextcloud/01.en.md
> +To create a self-signed certificate, run:
Great idea. It is simple to do that so I added a description of how to use let's encrypt.

2020-12-16 18:50 UTC, rericsson commented
I added instructions on using Let's Encrypt.

2020-12-17 10:16 UTC, rook59 approved these changes
Thank you, technical steps look good to me

2020-12-18 13:57 UTC, merged