Add Tutorial: Install TinyCP on a Hetzner Cloud Server
hetzneronline/community-content pull request #276
Opened 2020-11-23 21:01 UTC by luizoseas

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Luiz O. Melo Marques luizoseasmm@gmail.com

2020-12-02 08:12 UTC, rook59 requested changes
Thank you for your submission. Please take a look at my comments. The comments on the english version apply to both languages.

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/01.en.md
> +slug: "Install TinyCP on a Hetzner Cloud Server"
```suggestion
slug: "install-tinycp-on-a-hetzner-cloud-server"
```

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/01.en.md
> +author_img: "https://avatars1.githubusercontent.com/u/13169093?s=460&u=b1ca04b31e7bdfd01e62f8e8db42b96b8046cea9&v=4"
```suggestion
author_img: "https://avatars1.githubusercontent.com/u/13169093"
```

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/01.en.md
> +  You have done your remote access on a server on the Hetzner Cloud.
I guess you can remove that part and add a "VPS with root access" or similar as prerequisites. This tutorial works on any Ubuntu server.

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/01.en.md
> +   apt update && apt upgrade -y
You need `sudo` here when you use sudo below.

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/01.en.md
> +   sudo echo "deb http://repos.tinycp.com/ubuntu all main" | sudo tee /etc/apt/sources.list.d/tinycp.list
echo does not require sudo, only tee does

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/02.pt-br.md
> +slug: "Instalação TinyCP na Hetzner Cloud Server"
```suggestion
slug: "install-tinycp-on-a-hetzner-cloud-server"
```

2020-12-02 08:12 UTC, rook59 commented on tutorials/install-tinycp-on-a-hetzner-cloud-server/02.pt-br.md
> +path: "/tutorials/install-tinycp-on-a-hetzner-cloud-server"
```suggestion
path: "/tutorials/install-tinycp-on-a-hetzner-cloud-server/pt-br"
```

2020-12-02 19:06 UTC, luizoseas reviewed
Changes made

2020-12-09 14:13 UTC, rook59 approved these changes

2020-12-11 13:43 UTC, merged