OpenVPN setup for personal lab LAN access - PR
hetzneronline/community-content pull request #287
Opened 2021-01-19 10:57 UTC by jtnydv

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Jatin Yadav <jtnydv@protonmail.com>

2021-02-02 08:23 UTC, rook59 requested changes
Thank you for your tutorial! You are actually installing the proprietary "OpenVPN Access Server" product and not the OSS OpenVPN server software. The tutorial should clearly reflect this.
Can you please add small headlines about what you do in each step?
Please also take a look at our [tutorial template](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md) about the formatting of each step. You should replace `### Step X` with `## Step X`.
Your `NOTE` at the end should be a `Conclusion` instead.

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +author_img: "https://avatars3.githubusercontent.com/u/14368729?s=460&u=f4f0a30cb3f84681b5528f5a6a2669f456ee0b3d&v=4"
```suggestion
author_img: "https://avatars3.githubusercontent.com/u/14368729"

```

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +## OpenVPN setup for personal lab LAN access
```suggestion
## Introduction
```

The title is already mentioned in the title ;)

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +short_description: "This tutorial will guide you through the process of setting up an OpenVPN server so that you are able to access LAN from your local machine."
```suggestion
short_description: "This tutorial will guide you through the process of setting up an OpenVPN Access Server so that you are able to access LAN from your local machine."

```

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +title: "OpenVPN setup for personal lab LAN access"
```suggestion
title: "OpenVPN Access Server setup for personal lab LAN access"

```

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +First, let's go to the Network Settings under Configuration and change the "Hostname or IP Address." The value in that textbox should be the public IP address of the virtualization server.
> The value in that textbox should be the public IP address of the virtualization server.

What if the users IP address at home is a dynamic IP address? I guess setting up DynDNS and using a domain name instead of an IP address here should work. What do you think? Can you mention such a "workaround" for users with a dynamic IP?

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +```
This will be gone if the server is rebooted. What about a persistent iptables or ufw rule?

2021-02-02 08:23 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +slug: "setup-openvpn-lan-access"
I think you should also mention OpenVPN Access Server in the path and slug

2021-02-02 08:24 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +header_img: "header.jpg"
@leojakeson do we accept custom headers? I am not sure if this [header image](https://github.com/hetzneronline/community-content/blob/962e1cbb45e3c0a01b8eb4e770a3ccf61689d167/tutorials/setup-openvpn-lan-access/header.jpg) has some copyright

2021-02-08 18:00 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +slug: "setup-openvpn-lan-access"
Done the changes to the slug and path.

2021-02-08 18:01 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +title: "OpenVPN setup for personal lab LAN access"
Did the suggested change.

2021-02-08 18:02 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +short_description: "This tutorial will guide you through the process of setting up an OpenVPN server so that you are able to access LAN from your local machine."
Did the suggested change

2021-02-08 18:02 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +author_img: "https://avatars3.githubusercontent.com/u/14368729?s=460&u=f4f0a30cb3f84681b5528f5a6a2669f456ee0b3d&v=4"
Did the suggested change

2021-02-08 18:03 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +header_img: "header.jpg"
Please have a look and let me know, if this would be acceptable. If not, I'll remove it.

2021-02-08 18:03 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +## OpenVPN setup for personal lab LAN access
Made the suggested changes.

2021-02-08 18:04 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +First, let's go to the Network Settings under Configuration and change the "Hostname or IP Address." The value in that textbox should be the public IP address of the virtualization server.
The IP Address I am talking about here is the Hetzner Server Public IP address not the user's IP address. I hope that makes it clear.

2021-02-08 18:04 UTC, jtnydv commented on tutorials/setup-openvpn-lan-access/01.en.md
> +```
I haven't looked into iptables. I am not that fluent with iptables, I will try to find a workaround.

2021-02-08 18:06 UTC, jtnydv reviewed
Made the requested changes.

2021-02-08 18:09 UTC, jtnydv commented
> Thank you for your tutorial! You are actually installing the proprietary "OpenVPN Access Server" product and not the OSS OpenVPN server software. The tutorial should clearly reflect this.
> Can you please add small headlines about what you do in each step?
> Please also take a look at our [tutorial template](https://github.com/hetzneronline/community-content/blob/master/tutorial-template.md) about the formatting of each step. You should replace `### Step X` with `## Step X`.
> Your `NOTE` at the end should be a `Conclusion` instead.

Added the conclusion and changed the Markdown heading size.

2021-02-12 12:33 UTC, leojakeson commented on tutorials/setup-openvpn-lan-access/01.en.md
> +header_img: "header.jpg"
We don't yet support this feature (custom header images), though we are looking at implementing that in the future.

So for now, please remove it, thank you.

2021-02-17 07:09 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +header_img: "header.jpg"
@jtnydv the custom header_img  and header.jpg still needs to be removed :)

2021-02-17 07:10 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +```
Okay, would be definetely nice to have

2021-02-17 07:13 UTC, rook59 commented on tutorials/setup-openvpn-lan-access/01.en.md
> +First, let's go to the Network Settings under Configuration and change the "Hostname or IP Address." The value in that textbox should be the public IP address of the virtualization server.
Got it. I thought you were referring to a home LAN, but you are absolutely right if this is happening on a dedicated server with virtualization.

2021-02-22 12:31 UTC, rook59 reviewed
Thank you. Looks better to me now.
Last thing you would need to do is to remove the header_image tag and the header image itself.

2021-03-17 07:04 UTC, rook59 commented
@jtnydv can you please fix the last small things? afterwards it is ready to go

2021-03-23 10:05 UTC, jtnydv commented
Sorry for such delay. I've made the required changes as stated in the last comment. Please let me know if anything else is required of me. Thanks.

2021-03-23 11:06 UTC, rook59 approved these changes
Thanks

2021-03-24 14:15 UTC, merged

2021-04-02 07:02 UTC, jtnydv commented
Hey Team, is my article not eligible for the 50 USD Hetzner credits?

2021-04-08 07:57 UTC, leojakeson commented
Apologies for the late response, we just sent you an email with further instructions.