How to toggle password field in vuejs
hetzneronline/community-content pull request #337
Opened 2021-06-16 09:35 UTC by tomboe311

I have read and understood the Contributor's Certificate of Origin available at the end of 
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Thomas Boehringer <dev@tboehringer.de>

2021-06-16 09:49 UTC, tobiasgruber1995 requested changes

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.de.md
> +Dieses Tutorial zeigt wie in Vue.js 3.* wiederverwendbare "Components", anhand eines Passwortfelds mit einem Sichtbarkeit-Button, erstellt wird.
```suggestion
Dieses Tutorial zeigt, wie in Vue.js 3.* wiederverwendbare "Components" anhand eines Passwortfelds mit einem Sichtbarkeit-Button erstellt werden.
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.de.md
> +In dem Texteditor Deiner Wahl, öffne die neue HTML Datei und füge folgendes Basic HTML Code hinzu:
```suggestion
In dem Texteditor deiner Wahl, öffne die neue HTML Datei und füge folgenden Basic HTML Code hinzu:
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.de.md
> +* Wenn der `<button` angeklickt wird, die Methode `switchVisibility` wird ausgeführt und der `type` des `<input>` wird zwischen `"text"` und `"password"` gewechselt.
```suggestion
* Wenn der `<button>` angeklickt wird, wird die Methode `switchVisibility` ausgeführt und der `type` des `<input>` wird zwischen `"text"` und `"password"` gewechselt.
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.de.md
> +Am Ende des Bodys in die `index.html` wird die erstellte Datei aus Step 3.2 wie folgt eingebunden:
```suggestion
Am Ende des Bodys wird die erstellte Datei aus Step 3.2 wie folgt in die `index.html` eingebunden:
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.en.md
> +At the beginning, the directory structure of the project is creating with the `mkdir` command:
```suggestion
At the beginning, the directory structure of the project is created with the `mkdir` command:
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.en.md
> +* When the `<button` is clicked, execute the method `switchVisibility` and change the `type` in `<input>` between `"text"` and `"password"`.
```suggestion
* When the `<button>` is clicked, the method `switchVisibility` is executed and toggles the `type` in `<input>` between `"text"` and `"password"`.
```

2021-06-16 09:49 UTC, tobiasgruber1995 commented on tutorials/how-to-toggle-password-field-in-vuejs/01.en.md
> +The stylesheet is including in the `<head>` in the `index.html` file:
```suggestion
The stylesheet is included in the `<head>` in the `index.html` file:
```

2021-06-18 11:42 UTC, rook59 approved these changes
German path is wrong otherwise it looks good to me

2021-07-02 14:18 UTC, merged