Adding Tutorial for Adding SSH Key on a new Hetzner Instance
hetzneronline/community-content pull request #347
Opened 2021-07-13 11:44 UTC by hlbp

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Helmer Barcos helmer@barcos.co

2021-07-19 11:21 UTC, mhupfauer requested changes

2021-07-19 11:21 UTC, mhupfauer commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +ssh-keygen -t rsa -b 2048 -C "some comment here“.
ENISA recommends usage of at least 4096 for long time purposes.

2021-07-19 11:21 UTC, mhupfauer commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +By default this command will create a public and a private key named `id_rsa.pub `and `id_rsa` respectively and they will be saved on the path `~/.ssh/`. Its upto you if you want to add a passphrase
It should be really discouraged to use ssh keys without password armor if possible at all. For an enduser connecting to a server it should not be recommended to use keys without passphrase.

2021-07-21 09:22 UTC, hlbp commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +ssh-keygen -t rsa -b 2048 -C "some comment here“.
Thanks for pointing this. I changed it already.

2021-07-21 09:23 UTC, hlbp commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +By default this command will create a public and a private key named `id_rsa.pub `and `id_rsa` respectively and they will be saved on the path `~/.ssh/`. Its upto you if you want to add a passphrase
@mhupfauer  you are totally right. I updated this paragraph.

2021-07-27 13:05 UTC, rook59 commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +slug: "add-ssh-key-to-your-hetzner-instance"
I would suggest something like `add-ssh-key-to-hetzner-cloud` because `hetzner-instance` looks unclear to me

2021-07-28 09:52 UTC, hlbp commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +slug: "add-ssh-key-to-your-hetzner-instance"
@rook59  done! I think this this should be ready to go now!

2021-07-28 11:33 UTC, rook59 commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +slug: "add-ssh-key-to-your-hetzner-instance"
You would also need to change the folder name

2021-07-28 13:51 UTC, hlbp commented on tutorials/add-ssh-key-to-your-hetzner-instance/01.en.md
> +slug: "add-ssh-key-to-your-hetzner-instance"
@rook59 also done!

2021-07-29 09:47 UTC, rook59 approved these changes
LGTM

2021-07-29 09:51 UTC, mhupfauer approved these changes
LGTM

2021-08-02 23:16 UTC, closed without merging

2021-08-02 23:37 UTC, hlbp commented
@rook59 , @mhupfauer  I had to create another Pull Request. I hope this makes no conflicts. 
https://github.com/hetzneronline/community-content/pull/351