Adding Tutorial: Migration from CVS to Git
hetzneronline/community-content pull request #352
Opened 2021-08-02 23:49 UTC by hlbp

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Helmer Barcos helmer@barcos.co

2021-08-19 06:32 UTC, rook59 requested changes
Thank you for your submission.  
Why do you use cvs2svn instead of https://git-scm.com/docs/git-cvsimport?

2021-08-19 06:32 UTC, rook59 commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +short_description: "In this tutorial I will show you how to login to your Hetzner instance with a SSH Key"
Please update the description to match this tutorial

2021-08-19 06:32 UTC, rook59 commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +## Step 1 - Clone the [cvs2svn]() project and install it.
> [cvs2svn]()

What's this? Did you want to link anything?

2021-08-19 06:32 UTC, rook59 commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +  cd cvs2svn && make build && cd ...
build is not available

```
Supported make targets:
    man -- Create manpages for the main programs
    install -- Install software using distutils
    dist -- Create an installation package
    check -- Run cvs2svn tests
    pycheck -- Use pychecker to check cvs2svn Python code
    clean -- Clean up source tree and temporary directory

2021-08-20 08:15 UTC, hlbp commented
@rook59  thanks for your feedback. I updated the MR in order to attend your comments. 
 There is a warning on the website from git for the `git-cvsimport`. That is the reason why I used `cvs2git`. I also expended a couple of hours trying with `git-cvsimport` without any success.

> WARNING: git cvsimport uses cvsps version 2, which is considered deprecated; it does not work with cvsps version 3 and later. If you are performing a one-shot import of a CVS repository consider using cvs2git or cvs-fast-export.

2021-08-20 08:16 UTC, hlbp commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +short_description: "In this tutorial I will show you how to login to your Hetzner instance with a SSH Key"
done

2021-08-20 08:17 UTC, hlbp commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +## Step 1 - Clone the [cvs2svn]() project and install it.
Yes! the author's git repo of the project.

2021-08-20 08:17 UTC, hlbp commented on tutorials/how-to-migrate-a-cvs-repository-to-git/01.en.md
> +  cd cvs2svn && make build && cd ...
updated

2021-08-24 13:09 UTC, rook59 approved these changes
LGTM

2021-08-24 14:46 UTC, merged