install-and-configure-onlyoffice-docs-for-nextcloud
hetzneronline/community-content pull request #353
Opened 2021-08-10 10:44 UTC by kseniafedoruk

I have read and understood the Contributor's Certificate of Origin available at the end of
https://raw.githubusercontent.com/hetzneronline/community-content/master/tutorial-template.md
and I hereby certify that I meet the contribution criteria described in it.
Signed-off-by: Ksenia Fedoruk <kseniya.fedoruk@onlyoffice.com>

2021-08-11 10:22 UTC, mhupfauer requested changes

2021-08-11 10:22 UTC, mhupfauer commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +*	Your Nextcloud installed on the different machine
Your Nextcloud installed on **a** different machine

2021-08-11 10:22 UTC, mhupfauer commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +```shell=
$ curl -fsSL https://get.docker.com -o get-docker.sh
$ sh get-docker.sh

2021-08-11 10:22 UTC, mhupfauer commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +## Step 2 - Install Docker
Remove due to above comment, with docker install script and update step numbering

2021-08-11 10:22 UTC, mhupfauer commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +```shell=
For a persistent installation use a docker-compose.yml file and manage the container with compose.
This enables users to version config files and easily restore them on different machines.

2021-08-18 09:20 UTC, kseniafedoruk commented
Hey! I've made and committed the necessary changes to the article.

2021-08-18 09:24 UTC, mhupfauer commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +For a persistent installation use a docker-compose.yml file and manage the container with compose. This enables users to version config files and easily restore them on different machines.
Add this link: https://github.com/ONLYOFFICE/Docker-DocumentServer/blob/master/docker-compose.yml so people can get easily to the compose file.

2021-08-18 09:25 UTC, mhupfauer requested changes
One little change request :)
Otherwise this looks good!

2021-08-18 09:32 UTC, kseniafedoruk commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +For a persistent installation use a docker-compose.yml file and manage the container with compose. This enables users to version config files and easily restore them on different machines.
I've already added (the 2nd commit). And I see the link is available here https://github.com/kseniafedoruk/community-content/blob/master/tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md.

2021-08-18 09:40 UTC, kseniafedoruk commented
Thanks! The link is added.

2021-08-18 12:36 UTC, mhupfauer approved these changes

2021-08-19 09:45 UTC, rook59 commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +```shell=
Not sure if I like that part.. From https://docs.docker.com/engine/install/ubuntu/#install-using-the-convenience-script

> The convenience script is not recommended for production environments, but can be used as an example to create a provisioning script that is tailored to your needs.

What do you think?

2021-08-19 09:46 UTC, rook59 commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +Signed-off-by: [submitter's name and email address here]
Please sign off here

2021-08-19 10:10 UTC, kseniafedoruk commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +Signed-off-by: [submitter's name and email address here]
Done!

2021-08-20 09:27 UTC, kseniafedoruk commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +```shell=
We can get back to installing using the repository. Would it be better?

2021-08-23 15:36 UTC, kseniafedoruk commented
Hey! Can we move forward or is there any editing still needed?

2021-08-24 13:10 UTC, rook59 commented on tutorials/install-and-configure-onlyoffice-docs-for-nextcloud/01.en.md
> +```shell=
Both works, I would just prefer the previous one. We can keep it like that.

2021-08-24 13:11 UTC, rook59 approved these changes
Thank you for your submission!

2021-08-24 15:23 UTC, merged